// <auto-generated />
namespace ExternalApi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExternalSourcesAdd_ApiKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExternalSourcesAdd_ApiKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201704160755371_ExternalSources-Add_ApiKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
